# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "sobre"
  pageRef = "about"
  weight = 20

[[main]]
  name = "resumo"
  pageRef = "resume"
  weight = 30

#[[main]]
#  name = "projetos"
#  pageRef = "projects"
#  weight = 40

[[main]]
  name = "blog"
  pageRef = "posts"
  weight = 50

[[main]]
  name = "categorias"
  #pageRef = "posts"
  weight = 90

[[main]]
  name = "Arquitetura de Software"
  pageRef = "categories/Arquitetura de Software"
  parent = "categorias"
  weight = 20

[[main]]
  name = "Padrões de Projeto"
  parent = "categorias"
  pageRef = "categories/Padrões de Projeto"
  weight = 20

[[main]]
  name = "Algoritmos e Estrutura de Dados"
  parent = "categorias"
  pageRef = "categories/Algoritmos e Estrutura de Dados"
  weight = 20

#[[subnavigation]]
#  name = "Padrões de Projeto"
#  pageRef = "tags/hello"
#  weight = 10
#
#[[subnavigation]]
#  name = "Algoritmos e Estrutura de Dados"
#  pageRef = "tags/hello"
#  weight = 10
#
#[[subnavigation]]
#  name = "Arquitetura de Software"
#  #pre = "github"
#  pageRef = "categories/Arquitetura de Software"
#  weight = 20

#[[main]]
#  name = "categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "tags"
#  pageRef = "tags"
#  weight = 100


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "categorias"
  pageRef = "categories"
  weight = 20
